#!/bin/sh

exec 2>&1

export PYTHONPATH="$PYTHONPATH:$(hab pkg path habstack/keystone)/lib/python2.7/site-packages"
export LD_LIBRARY_PATH="$(hab pkg path core/pcre)/lib:$(hab pkg path core/libffi)/lib"

keystone-manage db_sync
keystone-manage bootstrap --bootstrap-password mypass
