#!/bin/sh

echo "Starting keystone (admin) ..."

{{pkg.path}}/bin/uwsgi {{pkg.path}}/bin/keystone-wsgi-admin

echo "Starting keystone (public) ..."

{{pkg.path}}/bin/uwsgi {{pkg.path}}/bin/keystone-wsgi-public
