#!/bin/sh

exec 2>&1

export PBR_VERSION="{{pkg.version}}"
export LD_LIBRARY_PATH="$(hab pkg path core/pcre)/lib:$(hab pkg path core/libffi)/lib"
export PYTHONPATH="{{pkg.path}}/lib/python2.7/site-packages:$(hab pkg path core/python2)/lib/python2.7/site-packages"

{{pkg.path}}/bin/uwsgi {{pkg.svc_path}}/config/keystone-uwsgi-admin.ini
{{pkg.path}}/bin/uwsgi {{pkg.svc_path}}/config/keystone-uwsgi-public.ini
